import { z } from 'zod';

/**
 * Server-side sanitization for the LLM-extracted booking payload.
 *
 * The model output (`payload` from a SYSTEM_BOOKING_CAPTURE action) is UNTRUSTED
 * input — it is generated by an LLM from free-text user speech, NOT validated
 * user form data. Never insert it raw. Every field is length-capped and (where
 * relevant) format-checked before it touches `tenant_appointments`.
 *
 * Models do NOT reliably populate the structured `payload` fields — they often
 * place the name/phone in the prose `summary` instead. `buildBookingCapture`
 * therefore extracts contact details from BOTH the structured payload AND the
 * raw utterance/summary (regex fallback), so capture is reliable regardless of
 * where the model chose to put the data.
 */

const PHONE_DIGITS_RE = /(\+?\d[\d ()-]{6,19}\d)/;

export const BookingCaptureSchema = z
  .object({
    firstName: z.string().trim().max(120).optional().nullable(),
    phone: z.string().trim().max(20).optional().nullable(),
    treatment: z.string().trim().max(200).optional().nullable(),
    preferredDate: z.string().trim().max(40).optional().nullable(),
    preferredTime: z.string().trim().max(40).optional().nullable(),
    notes: z.string().trim().max(500).optional().nullable(),
  })
  .strict();

export interface SanitizedBooking {
  firstName: string | null;
  phone: string | null;
  treatment: string | null;
  preferredDate: string | null;
  preferredTime: string | null;
  notes: string | null;
  /** True only when at least a phone OR a name is present — the minimum we persist. */
  hasContact: boolean;
}

function normalizePhone(value: string | null | undefined): string | null {
  if (!value) return null;
  // Preserve a single leading '+', then keep only digits, so LLM-formatted
  // phones ("0 8 2 1 2 3 4 5 6 7", "+27 (82) 123-4567") store compact digits.
  const plus = value.trim().startsWith('+') ? '+' : '';
  const digits = value.replace(/\D/g, '');
  if (digits.length < 7 || digits.length > 15) return null;
  return `${plus}${digits}`.slice(0, 20);
}

function extractPhoneFromText(...texts: (string | null | undefined)[]): string | null {
  for (const t of texts) {
    if (!t) continue;
    const m = t.match(PHONE_DIGITS_RE);
    if (m) {
      const norm = normalizePhone(m[1]);
      if (norm) return norm;
    }
  }
  return null;
}

// Name heuristics: "I'm Jill", "my name is Jill", "this is Jill", "I am Jill".
const NAME_RE = /\b(?:i(?:'m| am)|my name is|this is|name['’]?s)\s+([A-Z][a-z]{1,40})/i;

function extractNameFromText(...texts: (string | null | undefined)[]): string | null {
  for (const t of texts) {
    if (!t) continue;
    const m = t.match(NAME_RE);
    if (m && m[1]) return m[1].trim().slice(0, 120);
  }
  return null;
}

function coalesce(a: string | null, b: string | null): string | null {
  return a && a.length > 0 ? a : b && b.length > 0 ? b : null;
}

/**
 * Build a sanitized booking capture from the model's structured payload PLUS the
 * raw utterance/summary. Payload fields win when present; otherwise we fall back
 * to regex extraction from free text so capture never silently drops a booking
 * just because the model put the data in prose.
 */
export function buildBookingCapture(
  raw: unknown,
  text: string,
  summary?: string | null,
): SanitizedBooking {
  const obj = raw && typeof raw === 'object' && !Array.isArray(raw) ? raw : {};
  const parsed = BookingCaptureSchema.safeParse(obj);
  const v = parsed.success ? parsed.data : ({} as Record<string, never>);

  const phone = coalesce(normalizePhone(v.phone ?? null), extractPhoneFromText(text, summary));
  const firstName = coalesce(
    v.firstName && v.firstName.length > 0 ? v.firstName : null,
    extractNameFromText(text, summary),
  );
  const treatment = v.treatment && v.treatment.length > 0 ? v.treatment.slice(0, 200) : null;
  const preferredDate = v.preferredDate && v.preferredDate.length > 0 ? v.preferredDate.slice(0, 40) : null;
  const preferredTime = v.preferredTime && v.preferredTime.length > 0 ? v.preferredTime.slice(0, 40) : null;
  const notes = v.notes && v.notes.length > 0 ? v.notes.slice(0, 500) : null;

  return {
    firstName,
    phone,
    treatment,
    preferredDate,
    preferredTime,
    notes,
    hasContact: Boolean(firstName || phone),
  };
}

/**
 * @deprecated shim — kept for any caller that only has the raw payload. Prefer
 * `buildBookingCapture(raw, text, summary)` which adds text-fallback extraction.
 */
export function sanitizeBookingCapture(raw: unknown): SanitizedBooking | null {
  if (raw === null || typeof raw !== 'object' || Array.isArray(raw)) return null;
  const parsed = BookingCaptureSchema.safeParse(raw);
  if (!parsed.success) return null;
  const v = parsed.data;
  const phone = normalizePhone(v.phone ?? null);
  const firstName = v.firstName && v.firstName.length > 0 ? v.firstName : null;
  const treatment = v.treatment && v.treatment.length > 0 ? v.treatment : null;
  const preferredDate = v.preferredDate && v.preferredDate.length > 0 ? v.preferredDate : null;
  const preferredTime = v.preferredTime && v.preferredTime.length > 0 ? v.preferredTime : null;
  const notes = v.notes && v.notes.length > 0 ? v.notes : null;
  return {
    firstName,
    phone,
    treatment,
    preferredDate,
    preferredTime,
    notes,
    hasContact: Boolean(firstName || phone),
  };
}
